using System.Text.Json.Serialization;

namespace UnityMcpServer.Models;

/// <summary>
/// Metadata about a connected Unity Editor instance
/// </summary>
public class EditorMetadata
{
    /// <summary>
    /// Unique connection ID for this editor (generated by server)
    /// </summary>
    [JsonPropertyName("connectionId")]
    public string ConnectionId { get; set; } = string.Empty;

    /// <summary>
    /// Unity project name
    /// </summary>
    [JsonPropertyName("projectName")]
    public string ProjectName { get; set; } = string.Empty;

    /// <summary>
    /// Currently active scene in this editor
    /// </summary>
    [JsonPropertyName("activeScene")]
    public string ActiveScene { get; set; } = string.Empty;

    /// <summary>
    /// Scene path
    /// </summary>
    [JsonPropertyName("scenePath")]
    public string ScenePath { get; set; } = string.Empty;

    /// <summary>
    /// Machine name where this Unity editor is running
    /// </summary>
    [JsonPropertyName("machineName")]
    public string MachineName { get; set; } = string.Empty;

    /// <summary>
    /// Unity editor process ID
    /// </summary>
    [JsonPropertyName("processId")]
    public int ProcessId { get; set; }

    /// <summary>
    /// Unity version
    /// </summary>
    [JsonPropertyName("unityVersion")]
    public string UnityVersion { get; set; } = string.Empty;

    /// <summary>
    /// Data path (Assets folder location)
    /// </summary>
    [JsonPropertyName("dataPath")]
    public string DataPath { get; set; } = string.Empty;

    /// <summary>
    /// Platform (Windows, macOS, Linux)
    /// </summary>
    [JsonPropertyName("platform")]
    public string Platform { get; set; } = string.Empty;

    /// <summary>
    /// When this editor connected
    /// </summary>
    [JsonPropertyName("connectedAt")]
    public DateTime ConnectedAt { get; set; }

    /// <summary>
    /// Whether this editor is currently in play mode
    /// </summary>
    [JsonPropertyName("isPlaying")]
    public bool IsPlaying { get; set; }

    /// <summary>
    /// Tool profile preference for this editor (minimal, standard, full)
    /// Controls which MCP tools are exposed to LLM clients
    /// </summary>
    [JsonPropertyName("toolProfile")]
    public string ToolProfile { get; set; } = "standard";

    /// <summary>
    /// Display name for this editor (auto-generated from metadata)
    /// </summary>
    [JsonPropertyName("displayName")]
    public string DisplayName => $"{ProjectName} - {ActiveScene} ({MachineName})";
}
